/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRYIO_HARDWARE_JNI */

#ifndef _Included_CRYIO_HARDWARE_JNI
#define _Included_CRYIO_HARDWARE_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CRYIO_HARDWARE_JNI
 * Method:    init
 * Signature: (JJ[B[B)V
 */
JNIEXPORT void JNICALL Java_CRYIO_1HARDWARE_1JNI_init
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jbyteArray);

/*
 * Class:     CRYIO_HARDWARE_JNI
 * Method:    update
 * Signature: ([BJ[BJ)C
 */
JNIEXPORT jchar JNICALL Java_CRYIO_1HARDWARE_1JNI_update
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     CRYIO_HARDWARE_JNI
 * Method:    doFinal
 * Signature: ([BJ[BJ)C
 */
JNIEXPORT jchar JNICALL Java_CRYIO_1HARDWARE_1JNI_doFinal
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
